# SPDX-FileCopyrightText: 2024 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "DESY and the Constellation authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "subprojects/*.wrap"
SPDX-FileCopyrightText = "Meson WrapDB"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "cxx/constellation/core/external/md5.h"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "cxx/controllers/MissionControl/MissionControl.qrc",
  "cxx/controllers/MissionControl/MissionControl.ui",
  "cxx/listeners/Observatory/Observatory.qrc",
  "cxx/listeners/Observatory/Observatory.ui",
  "cxx/listeners/Observatory/LogDialog.ui"
]
SPDX-FileCopyrightText = "DESY and the Constellation authors"
SPDX-License-Identifier = "EUPL-1.2"
