Device:
    Configuration:
        Device: 2410
        #use 'COM<n>' for Windows (n is integer)
        #use '/dev/ttyUSB<n>' for Linux/MAC (n is integer)
        #might need to: 'sudo chmod a+rw /dev/ttyUSB<n>'
        Port: '/dev/ttyUSB0'
        Baudrate: 19200
        TimeOut: 2
        #NOTE: On Keithley: set RS-232 connection to have this baud rate, 8 bits, even partiy, <CR+LF> terminator

        Measure: 'I' # Can be V, I, or R
        ComplianceMeasure: 0.000105 # [A] when sourcing V
        RangeMeasure:      0.001 # [A]

        #For auto range
        AutoRangeMeasure: 'ON'

        # For the voltage sourcing
        OVPSource:  20 # [V]
        RangeSource:       10.0 # [V]
        MinAllowedSource: -0.4 # [V]
        MaxAllowedSource: 0.4 # [V]
        SafeLevelSource: 0.0 # [V]

        #To get the display to show sensibly.
        #Not super important, since we read the current off anyway.
        TriggerCount: 2
        TriggerDelay: 0.001
        WaitRead: 0.05

        SettlingTime: 0.1
SetVoltage:
    V_Step:  0.05  # [V]
    V_Set:   0.4  # [V]
CurrentPublish:
    Interval: 1 # [s]
