# SPDX-FileCopyrightText: 2025 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

name: Documentation

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: gitlab.desy.de:5555/constellation/build-images/fedora-sphinx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ignore git ownership warnings
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Set up Python Venv
        uses: getsentry/action-setup-venv@v2.2.0
        with:
          python-version: "3.11"
          cache-dependency-path: pyproject.toml
          install-cmd: |
            pip install --upgrade pip setuptools meson-python meson ninja

      - name: Install Constellation
        run: pip install --no-build-isolation -e .[docs]

      - name: Generate Doxygen
        run: |
          make -C docs doxygen

      - name: Build documentation
        run: |
          make -C docs html

      - name: Check Spelling
        run: |
          make -C docs spelling

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/build/html/
